name: test
namespace: test
type: deployment
labelSelector:
  app: app-svc
  version: v4
containerName: app-svc
commandArgs:
  - /app/app
nodeHost: 192.168.157.33
nodePort: 30035
projectRootDir: /projects/go/src/app
debugExePath: /root/app
dlvExePath: /root/dlv
